### ISSUE TITLE
adbctool UnicodeDecodeError

### ISSUE THREAD

**Issue by iverson-fa** [wheelos-tools/whl-dbc#5]
When I use dbc files in [opendbc rep](https://github.com/commaai/opendbc), adbctool works.
But when I use my own dbc , error occured as belowed:
```
Traceback (most recent call last):
  File "/home/dafa/.local/bin/adbctool", line 8, in <module>
    sys.exit(main())
  File "/home/dafa/.local/lib/python3.8/site-packages/adbctool/gen.py", line 61, in main
    if not extract_dbc_meta(args.dbc_file, protocol_conf_file, args.car_type,
  File "/home/dafa/.local/lib/python3.8/site-packages/adbctool/extract_dbc_meta.py", line 81, in extract_dbc_meta
    for line in fp:
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 2892: invalid start byte
```
[mc-ch_agv-1.4.2.dbc.txt](https://github.com/daohu527/adbctool/files/15262726/mc-ch_agv-1.4.2.dbc.txt)

Please help me check , thank you.

**Comment by daohu527** [comment]
The error caused by the file has invalid utf-8 character. In line 99
```
 SG_ BATTERY_TEMPERATURE : 48|16@1- (1,0) [-40|110] "¡æ"  HOST_PC
```
the  "¡æ" seems invalid, replace "" will work

## check file is utf-8
``` python
import codecs

def find_non_utf8_chars(filename):
  with codecs.open(filename, encoding='utf-8') as f:
    try:
        for line_num, line in enumerate(f):
            print("{} {}".format(line_num, line))
    except UnicodeDecodeError as e:
        print(e.start)
```

**Comment by iverson-fa** [comment]
Thank you @daohu527
